---
# See http://mumble-ruby-pluginbot.readthedocs.io/en/master/explain_the_config.html for the documentation of this config file.

config:
  version: 2.1

debug: true
language: en

main:
  tempdir: "/home/botmaster/temp/"
  logfile: "/home/botmaster/logs/bot1.log"
  ducking: false
  automute_if_alone: true
  stop_on_unregistered: true
  channel_notify: 0
  controllable: true
  control:
    string: "."
    message:
      private_only: false
      registered_only: true
    historysize: 20
  display:
    comment:
      set: true
  user:
    superuser:
      72x60721xx216x4xx017f3x1x476d4358x48x648: dafoxia
      1234567890ABCDEFGHIJKLMNOPQRSTUVWXYZ1234: anotheruser
    banned:
      123452342348234782937ckjfvo32ckj20938473: user3
      df92lkjvdkfj2okdfh20398vhj209eu2hjd092hn: anotherusername4
    bound: # "1234567890ABCDEFGHIJKLMN"
  certfolder: "/home/botmaster/certs/"
  fifo: "/home/botmaster/mpd1/mpd.fifo"
  logo: "../config/logo/logo.html"
  timer:
    ticks:  3600
  blacklisted_commands: ""

mumble:
  use_vbr: true
  bitrate: 72000
  host: m.natenom.com
  port: 64738
  name: "MumbleRubyPluginbot"
  password: ''
  channel: Bottest
