---
config:
  version: 2.1 # Do not change this :)

debug: true
language: en # The language the bot should use. Currently available languages are en and de. FIXME

main:
  remoteui: false
  tempdir: "/home/botmaster/temp/"
  logfile: "/home/botmaster/logs/bot1.log"
  ducking: false # If true the bot automatically reduces its volume while users in the channel are talking.
  automute_if_alone: true # The bot automatically mutes itself if he is alone in a channel.
  stop_on_unregistered: true # The bot pauses the music or stops a radiostream if an unregistered user enters the channel.
  channel_notify: 0   #   Calculating value for 'channel_notify'
                      #
                      # Add all values for the desired channel notification
                      #
                      # 1    send message when volume change
                      # 2    send message when database update
                      # 4    send message when random mode changed
                      # 8    send message when single mode changed
                      # 16   send message when crossfading changed
                      # 32   send message when consume-mode changed
                      # 64   send message when repeat-mode changed
                      # 128  send message when state changes
                      # ------
                      #
                      # sum = value
  controllable: true # Bot is only controllable if this is set to true. If false it will ignore all text commands.
  control:
    string: "." # This is the character/string a user must prepend to text commands. The bot ignores commands not starting with that character/string.
    message:
      private_only: false # If true the bot reacts only to private messages and not to channel messages. If false, the bot reacts to channel and private messages.
      registered_only: true # If true the bot reacts only to registered users. If false also unregistered users can control the bot.
    historysize: 20 # Store this many entries in the command history of the bot.
  display:
    comment:
      set: true # If true the bot sets its comment to display the current music that is being played.
  #need_binding: false # If true the bot reacts only if a user used the bind command.

  user:
    # You can define several superusers here. To get a users hash use the command "showhash", see "internals".
    # The commands "reset", "set" and "settings" can only be used by the defined superusers.
    # Safety Information: All predefined entries for superuser and banned are only there to show you how it works, they will never work.
    superuser:
      72x60721xx216x4xx017f3x1x476d4358x48x648: dafoxia
      1234567890ABCDEFGHIJKLMNOPQRSTUVWXYZ1234: anotheruser

    # Here the same applies as for "superuser" but these users will not be able to control the bot at all. The bot will ignore them completely.
    banned:
      123452342348234782937ckjfvo32ckj20938473: user3
      df92lkjvdkfj2okdfh20398vhj209eu2hjd092hn: anotherusername4

    # Only ONE user hash as a string. If definied nobody will be able to use the bind command anymore but the defined user. The blacklist command can only be used after being bound.
    bound: # "1234567890ABCDEFGHIJKLMN"

  certfolder: "/home/botmaster/certs/" # In this folder the bot automatically creates an openssl certificate per username you set up. See mumble: name.
  fifo: "/home/botmaster/mpd1/mpd.fifo" # This fifo must also be used by the MPD the bot connects to.
  logo: "../config/logo/logo.html" # A relative path to the logo the bot uses.
  timer:
    ticks:  3600
  blacklisted_commands: "" # Here you can disable specific commands. Be aware that currently the bot checks this very stupid. That means that it checks only the beginning of a word. For example if you blacklist set then settings is also blacklisted.

mumble:
  use_vbr: true # If 1, "yes" or true the bot encodes with a variable bitrate. If 0, "no" nor false it encodes with a constant bitrate.
  bitrate: 72000 # The overall bandwidth the bot is allowed to use. Please note that the bot is able to ask the server for its maximum bandwidth and so can reduce its bitrate if you set it higher than possible.
  host: m.natenom.com # The hostname or IP address of the Mumble server your bot connects to.
  port: 64738 # The port of the Mumble server your bot connects to.
  name: "MumbleRubyPluginbot" # The name of your bot. Be aware that on most servers you are not allowed to use white spaces or other special characters.
  password: '' # FIXME
  channel: Bottest # The channel the bot connects to. This is also the channel the bot tries to enter if you command it to "gotobed".
