---
config:
  version: 2.1

:debug: true
:language: en

main:
  tempdir: "/home/botmaster/temp/"
  ducking: false
  automute: true
  channel_notify: 0
  controllable: true
  control:
    string: "."
    message:
      private_only: false
      registered_only: true
      stop_on_unregistered: true
    historysize: 20
  display:
    comment: true
  need_binding: false
  bound: nobody
  certfolder: "/home/botmaster/certs/"
  fifo: "/home/botmaster/mpd1/mpd.fifo"
  logo: "logo/logo.html"
  timer:
    ticks:  3600
  superpassword: "kaguBe gave me all the power and I want to "

mumble:
  use_vbr: 1
  bitrate: 72000
  host: m.natenom.com
  port: 64738
  name: MumbleRubyPluginbot
  password: ''
  channel: Bottest
