---
# Please take a look into the full default configuration file located in
# the config/ directory if you need assistance for the settings.
# Also every plugin does have its own configuration file, see plugins/*.yml.
#
# All settings that you set here will overwrite those from the
# default configuration file config/config.yml and also those from every single
# plugin configuration file (plugins/*.yml).

config:
  version: 2.1

debug: true
language: en

main:
  ducking: false
  automute_if_alone: true
  stop_on_unregistered: true
  control:
    string: "."
    message:
      private_only: false
      registered_only: true
    historysize: 20
  fifo: "/home/botmaster/mpd1/mpd.fifo"
  user:
    # You can define several superusers here. To get a users hash use the command "showhash", see "internals".
    # The commands "reset", "set" and "settings" can only be used by the defined superusers.
    # Safety Information: All predefined entries for superuser and banned are only there to show you how it works, they will never work.
    superuser:
      72x60721xx216x4xx017f3x1x476d4358x48x648: dafoxia
      1234567890ABCDEFGHIJKLMNOPQRSTUVWXYZ1234: anotheruser

    # Here the same applies as for "superuser" but these users will not be able to control the bot at all. The bot will ignore them completely.
    banned:
      123452342348234782937ckjfvo32ckj20938473: user3
      df92lkjvdkfj2okdfh20398vhj209eu2hjd092hn: anotherusername4

    # Only ONE user hash as a string. If definied nobody will be able to use the bind command anymore but the defined user. The blacklist command can only be used after being bound.
    bound: # "1234567890ABCDEFGHIJKLMN"

mumble:
  use_vbr: 1
  bitrate: 72000
  host: m.natenom.com
  port: 64738
  name: MumbleRubyPluginbot
  password: ''
  channel: Bottest

plugin:
  mpd:
    volume: 65
    host: localhost
    port: 7701
  idle:
    maxidletime: 600 #in seconds
    idleaction: 'channel' #Can be "deafen" or "channel" different to let the bot join his default channel.
